USE [master]
GO

/****** Object:  Database [BibleStudyGuide]    Script Date: 19/03/2019 4:44:24 PM ******/
CREATE DATABASE [BibleStudyGuide]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BibleStudyGuide', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BibleStudyGuide.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BibleStudyGuide_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BibleStudyGuide_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BibleStudyGuide].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BibleStudyGuide] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET ARITHABORT OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BibleStudyGuide] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BibleStudyGuide] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BibleStudyGuide] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BibleStudyGuide] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET RECOVERY FULL 
GO

ALTER DATABASE [BibleStudyGuide] SET  MULTI_USER 
GO

ALTER DATABASE [BibleStudyGuide] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BibleStudyGuide] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BibleStudyGuide] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BibleStudyGuide] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BibleStudyGuide] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BibleStudyGuide] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BibleStudyGuide] SET  READ_WRITE 
GO

